# Generated by Django 5.0 on 2026-01-09 16:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('families', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='用户名')),
                ('display_name', models.CharField(blank=True, max_length=100, verbose_name='显示名称')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号')),
                ('role', models.CharField(choices=[('super_admin', '超级管理员'), ('family_admin', '家庭管理员'), ('family_member', '家庭成员')], default='family_member', max_length=20, verbose_name='角色')),
                ('face_registered', models.BooleanField(default=False, verbose_name='已注册人脸')),
                ('face_encodings_count', models.IntegerField(default=0, verbose_name='人脸照片数量')),
                ('status', models.CharField(choices=[('active', '正常'), ('inactive', '未激活'), ('suspended', '已停用')], default='active', max_length=20, verbose_name='账户状态')),
                ('is_active', models.BooleanField(default=True, verbose_name='账户激活')),
                ('is_staff', models.BooleanField(default=False, verbose_name='管理员权限')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='注册时间')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='最后登录')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_users', to=settings.AUTH_USER_MODEL, verbose_name='邀请人')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='families.family', verbose_name='所属家庭')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'users',
                'ordering': ['-date_joined'],
                'indexes': [models.Index(fields=['username'], name='users_usernam_baeb4b_idx'), models.Index(fields=['email'], name='users_email_4b85f2_idx'), models.Index(fields=['role'], name='users_role_0ace22_idx'), models.Index(fields=['family'], name='users_family__d8ad33_idx')],
            },
        ),
    ]
