# Generated by Django 5.0 on 2026-01-09 16:40

import django.utils.timezone
import families.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=100, verbose_name='家庭名称')),
                ('family_code', models.CharField(db_index=True, default=families.models.generate_family_code, max_length=20, unique=True, verbose_name='家庭邀请码')),
                ('max_members', models.IntegerField(default=20, verbose_name='最大成员数')),
                ('description', models.TextField(blank=True, verbose_name='家庭描述')),
                ('settings_json', models.JSONField(blank=True, default=dict, verbose_name='家庭设置')),
                ('status', models.CharField(choices=[('active', '正常'), ('inactive', '停用')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '家庭',
                'verbose_name_plural': '家庭',
                'db_table': 'families',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='邀请码')),
                ('username_for', models.CharField(max_length=50, verbose_name='指定用户名')),
                ('display_name_for', models.CharField(blank=True, max_length=100, verbose_name='指定显示名称')),
                ('max_uses', models.IntegerField(default=1, verbose_name='最大使用次数')),
                ('used_count', models.IntegerField(default=0, verbose_name='已使用次数')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('status', models.CharField(choices=[('active', '有效'), ('used', '已使用'), ('expired', '已过期'), ('revoked', '已撤销')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '邀请码',
                'verbose_name_plural': '邀请码',
                'db_table': 'invite_codes',
                'ordering': ['-created_at'],
            },
        ),
    ]
