# Generated by Django 5.0 on 2026-01-09 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_families', to=settings.AUTH_USER_MODEL, verbose_name='家庭管理员'),
        ),
        migrations.AddField(
            model_name='invitecode',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_invites', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='invitecode',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_codes', to='families.family', verbose_name='所属家庭'),
        ),
        migrations.AddIndex(
            model_name='invitecode',
            index=models.Index(fields=['code'], name='invite_code_code_bdf127_idx'),
        ),
        migrations.AddIndex(
            model_name='invitecode',
            index=models.Index(fields=['family', 'status'], name='invite_code_family__3c8954_idx'),
        ),
    ]
