# Generated by Django 5.0 on 2026-01-09 16:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceEncoding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding_vector', models.BinaryField(verbose_name='特征向量')),
                ('encoding_json', models.JSONField(blank=True, default=dict, verbose_name='特征向量JSON')),
                ('photo_path', models.CharField(max_length=255, verbose_name='照片路径')),
                ('quality_score', models.FloatField(blank=True, null=True, verbose_name='质量评分')),
                ('is_primary', models.BooleanField(default=False, verbose_name='主要特征')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '人脸特征',
                'verbose_name_plural': '人脸特征',
                'db_table': 'face_encodings',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmotionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(choices=[('angry', '愤怒'), ('disgust', '厌恶'), ('fear', '恐惧'), ('happy', '快乐'), ('sad', '悲伤'), ('surprise', '惊讶'), ('neutral', '中性')], max_length=50, verbose_name='主要表情')),
                ('confidence', models.FloatField(verbose_name='置信度')),
                ('all_probabilities', models.JSONField(default=dict, verbose_name='所有表情概率')),
                ('photo_path', models.CharField(blank=True, max_length=255, verbose_name='照片路径')),
                ('face_encoding_match', models.BooleanField(default=False, verbose_name='人脸匹配')),
                ('ai_analysis', models.JSONField(default=dict, verbose_name='AI分析')),
                ('context_info', models.JSONField(default=dict, verbose_name='上下文信息')),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='记录时间')),
                ('checkin_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emotion_records', to='checkins.checkinrecord', verbose_name='关联打卡记录')),
            ],
            options={
                'verbose_name': '表情记录',
                'verbose_name_plural': '表情记录',
                'db_table': 'emotion_records',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
