# Generated by Django 5.0 on 2026-01-09 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emotions', '0001_initial'),
        ('families', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotionrecord',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emotion_records', to='families.family', verbose_name='家庭'),
        ),
    ]
