# Generated by Django 5.0 on 2026-01-09 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emotions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emotionrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_records', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='faceencoding',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_encodings', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddIndex(
            model_name='emotionrecord',
            index=models.Index(fields=['user', 'recorded_at'], name='emotion_rec_user_id_af834a_idx'),
        ),
        migrations.AddIndex(
            model_name='emotionrecord',
            index=models.Index(fields=['family', 'recorded_at'], name='emotion_rec_family__54ea14_idx'),
        ),
        migrations.AddIndex(
            model_name='emotionrecord',
            index=models.Index(fields=['emotion'], name='emotion_rec_emotion_1f1e22_idx'),
        ),
        migrations.AddIndex(
            model_name='faceencoding',
            index=models.Index(fields=['user', 'is_primary'], name='face_encodi_user_id_e0732a_idx'),
        ),
    ]
