# Generated by Django 5.0 on 2026-01-09 16:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckinRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_time', models.DateTimeField(verbose_name='打卡时间')),
                ('scheduled_time', models.DateTimeField(blank=True, null=True, verbose_name='计划时间')),
                ('status', models.CharField(choices=[('on_time', '准时'), ('late', '迟到'), ('missed', '缺勤')], max_length=20, verbose_name='状态')),
                ('face_verified', models.BooleanField(default=False, verbose_name='人脸验证')),
                ('emotion_detected', models.CharField(blank=True, max_length=50, verbose_name='检测表情')),
                ('emotion_confidence', models.FloatField(blank=True, null=True, verbose_name='表情置信度')),
                ('emotion_probs', models.JSONField(default=dict, verbose_name='所有表情概率')),
                ('photo_path', models.CharField(blank=True, max_length=255, verbose_name='照片路径')),
                ('ai_analysis', models.TextField(blank=True, verbose_name='AI分析')),
                ('location', models.JSONField(blank=True, default=dict, verbose_name='位置信息')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '打卡记录',
                'verbose_name_plural': '打卡记录',
                'db_table': 'checkin_records',
                'ordering': ['-checkin_time'],
            },
        ),
        migrations.CreateModel(
            name='CheckinTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100, verbose_name='任务名称')),
                ('task_type', models.CharField(choices=[('daily', '每日打卡'), ('weekly', '每周打卡'), ('custom', '自定义')], max_length=20, verbose_name='任务类型')),
                ('target_members', models.JSONField(default=list, help_text='成员ID列表', verbose_name='目标成员')),
                ('schedule_config', models.JSONField(default=dict, verbose_name='调度配置')),
                ('reminder_config', models.JSONField(default=dict, verbose_name='提醒配置')),
                ('emotion_threshold', models.JSONField(default=dict, verbose_name='情绪阈值设置')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '打卡任务',
                'verbose_name_plural': '打卡任务',
                'db_table': 'checkin_tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
