# Generated by Django 5.0 on 2026-01-09 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkins', '0002_initial'),
        ('families', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_records', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='checkintask',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='checkintask',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_tasks', to='families.family', verbose_name='所属家庭'),
        ),
        migrations.AddField(
            model_name='checkinrecord',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='checkins.checkintask', verbose_name='任务'),
        ),
        migrations.AddIndex(
            model_name='checkintask',
            index=models.Index(fields=['family', 'is_active'], name='checkin_tas_family__accd5d_idx'),
        ),
        migrations.AddIndex(
            model_name='checkinrecord',
            index=models.Index(fields=['task', 'user'], name='checkin_rec_task_id_3f2843_idx'),
        ),
        migrations.AddIndex(
            model_name='checkinrecord',
            index=models.Index(fields=['family', 'checkin_time'], name='checkin_rec_family__11e435_idx'),
        ),
        migrations.AddIndex(
            model_name='checkinrecord',
            index=models.Index(fields=['status'], name='checkin_rec_status_eb45ff_idx'),
        ),
    ]
