# Generated by Django 5.0 on 2026-01-09 16:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('email', '邮件'), ('sms', '短信'), ('push', '推送'), ('in_app', '站内信')], max_length=20, verbose_name='通知类型')),
                ('recipient_email', models.EmailField(blank=True, max_length=254, verbose_name='接收邮箱')),
                ('subject', models.CharField(max_length=200, verbose_name='主题')),
                ('content', models.TextField(verbose_name='内容')),
                ('related_type', models.CharField(blank=True, max_length=50, verbose_name='关联类型')),
                ('related_id', models.BigIntegerField(blank=True, null=True, verbose_name='关联ID')),
                ('status', models.CharField(choices=[('pending', '待发送'), ('sent', '已发送'), ('failed', '发送失败'), ('read', '已读')], default='pending', max_length=20, verbose_name='状态')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
